name: quotidian-component-library-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Test runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
